AspNetMvcBlog/App.Web.Mvc/Models/NavbarViewModel.cs
using App.Web.Mvc.Data.Entity;

namespace App.Web.Mvc.Models
{
    public class NavbarViewModel
    {
        public IEnumerable<Category> Categories { get; set; }
        public IEnumerable<Page> Pages { get; set; }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/AuthController.cs
using App.Persistence.Data;
using App.Persistence.Data.Entity;
using App.Persistence.DTOs;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.Json;

namespace App.Web.Mvc.Controllers
{
    public class AuthController : Controller
    {
        private readonly AppDbContext appDbContext;

        public AuthController(AppDbContext appDbContext)
        {
            this.appDbContext = appDbContext;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterUserDto model)
        {
            if (!ModelState.IsValid)
            {
                RedirectToAction(nameof(Register), new { model });
            }

            if (model == null)
            {
                RedirectToAction(nameof(Index), "Home");
            }

            bool alreadyRegistered = appDbContext.User.Any(user => user.UserEmail == model.UserEmail);

            if (alreadyRegistered)
            {
                ModelState.AddModelError("Email", "Boyle bir email adresi zaten mevcut");

                ViewBag.RegisterationMessage = "Kayit basarisiz oldu";
                RedirectToAction(nameof(Register));
            }

            else
            {
                var dataModel = new User()
                {
                    UserEmail = model.UserEmail,
                    UserName = model.UserName,
                    UserSurname = model.UserSurname,
                    UserPassword = model.UserPassword,

                };

                appDbContext.Add(dataModel);
                appDbContext.SaveChanges();
                ViewBag.RegisterationMessage = "Kayit basari ile gerceklestirildi"; //bu konuda bir şey düşünün..

                return RedirectToAction(nameof(Index), "Home", new { area = "" });
            }
            return View();
        }

        [HttpGet]
        public IActionResult Login(string? redirectUrl)
        {

            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginUserDto model)
        {
            if (model == null)
            {
                return RedirectToAction(nameof(Login));
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = appDbContext.User.FirstOrDefault(t => t.UserEmail == model.UserEmail && t.UserPassword == model.UserPassword);

            if (user == null)
            {
                ModelState.AddModelError(nameof(model.UserPassword), "Kullanıcı kodu veya şifreniz hatalı");
                return View(model);
            }

            if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
            {
                string userJson = JsonSerializer.Serialize<User>(user);
                HttpContext.Session.SetString("user", userJson);
                HttpContext.Session.SetInt32("isLoggedIn", 1);
            }

            #region claim
            var claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, user.UserName),
                new Claim(ClaimTypes.Surname, user.UserSurname),
                new Claim(ClaimTypes.Email, user.UserEmail)

            };

            var claimsIdentity = new ClaimsIdentity(claims,
            CookieAuthenticationDefaults.AuthenticationScheme);

            #endregion

            return RedirectToAction(nameof(Index), "Home", new { area = "" });

        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();

            //HttpContext.Session.Remove("user");

            return Redirect("/");

        }

        public IActionResult ForgotPassword()
        {
            return View();
        }

    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Search(string query, int page)
        {
            return View();
        }

        public IActionResult Detail(int id)
        {
            return View();
        }

    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers
{
    public class PageController : Controller
    {
		[Route("Detay")]// page detail sayfasına route ile detay yazdım(task6)
		public IActionResult Detail(int id)
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers
{
    public class PostController : Controller
    {
		[Route("Icerik")]
		public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Views/Shared/Components/Navbar/Default.cshtml
@model App.Persistence.Models.NavbarViewModel
@using System.Text.Json;
@using App.Persistence.Data.Entity;
@inject IHttpContextAccessor _currentPageInfo
@{
  var isLoggedIn = _currentPageInfo.HttpContext.Session.GetInt32("isLoggedIn");
  var sessionUser = _currentPageInfo.HttpContext.Session.Get("user");
  User loggedInUser = null;
  if (sessionUser != null)
  {

    loggedInUser = JsonSerializer.Deserialize<User>(sessionUser);
  }
}



<header class="header-top bg-grey justify-content-center">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-2 col-md-4 text-center d-none d-lg-block">
                <a class="navbar-brand " asp-controller="Home" asp-action="Index">
                    <img src="~/dist/images/logo.png" alt="" class="img-fluid">
                </a>
            </div>
            <div class="search-wrap">
                <div class="overlay">
                    <form asp-action="Search" asp-controller="Blog"  class="search-form">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-10 col-9">
                                    <input type="text" class="form-control" placeholder="Search..." />
                                </div>
                                <div class="col-md-2 col-3 text-right">
                                    <div class="search_toggle toggle-wrap d-inline-block">
                                        <i class="ti-close"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-8 col-md-12">
                <nav class="navbar navbar-expand-lg navigation-2 navigation">
                    <a class="navbar-brand text-uppercase d-lg-none" asp-controller="Home" asp-action="Index">
                        <img src="~/dist/images/logo.png" alt="" class="img-fluid">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="ti-menu"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar-collapse">
                        <ul id="menu" class="menu navbar-nav mx-auto">
                           <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Index">
                                    Home
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Blog Posts
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                    <a class="dropdown-item" asp-controller="Blog" asp-action="Detail">Detail</a>
                                    <a class="dropdown-item" asp-controller="Blog" asp-action="Search">Search</a>
                                </div>
                            </li>
                            <li class="nav-item"><a asp-controller="Page" asp-action="Detail" class="nav-link">About</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Category
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                                    <a asp-action="Lifestyle" asp-controller="Category">Lifestyle</a>
                                    <a asp-action="Travel" asp-controller="Category">Travel</a>
                                    <a asp-action="Explore" asp-controller="Category">Explore</a>
                                    <a asp-action="Weekends" asp-controller="Category">Weekends</a>
                                    <a asp-action="Health" asp-controller="Category">Health</a>
                                </div>
                                </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Post" asp-action="Index">
                                    Post Format
                                </a>
                            </li>
                            <li class="nav-item"><a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a></li>
                        </ul>
                        <div class="text-right search">
                            <div class="search_toggle d-none d-lg-block"><i class="ti-search"></i></div>
                        </div>
                        <ul class="list-inline mb-0 d-block d-lg-none">
                            <li class="list-inline-item"><a href="https://www.facebook.com/"><i class="ti-facebook"></i></a></li>
                            <li class="list-inline-item"><a href="https://twitter.com/"><i class="ti-twitter"></i></a></li>
                            <li class="list-inline-item"><a href="https://www.linkedin.com/"><i class="ti-linkedin"></i></a></li>
                            <li class="list-inline-item"><a href="https://tr.pinterest.com/"><i class="ti-pinterest"></i></a></li>
                        </ul>
                    </div>
                </nav>
            </div>

            <div class="col-lg-2 col-md-4 col-6">
                <div class="header-socials-2 text-right d-none d-lg-block">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="https://www.facebook.com/" target="_blank"><i class="ti-facebook"></i></a></li>
                        <li class="list-inline-item"><a href="https://twitter.com/" target="_blank"><i class="ti-twitter"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.linkedin.com/" target="_blank"><i class="ti-linkedin"></i></a></li>
                        <li class="list-inline-item"><a href="https://tr.pinterest.com/" target="_blank"><i class="ti-pinterest"></i></a></li>

                        @if (isLoggedIn == 1)
                        {
                            <li class ="list-inline-item"><a asp-area="" asp-controller="Auth" asp-action="Logout" class="btn btn-secondary me-2 rounded">Logout</a></li>
                            <li class="list-inline-item" style="color: red;">@loggedInUser.UserName @loggedInUser.UserSurname</li>

                        }
                        else
                        {
                            <li class="list-inline-item">
                                <a asp-controller="Auth" asp-action="Login" class="btn btn-secondary me-2 rounded">Kullanıcı Girişi</a>
                            </li>
                            <li class="list-inline-item">
                                <a asp-controller="Auth" asp-action="Register" class="btn btn-secondary me-2 rounded">Sign In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Auth" asp-action="Login">Yönetici Girişi</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>

        </div>   
    </div>
</header>


            


         