AspNetMvcBlog/App.Web.Mvc/Areas/Admin/Controllers/CategoryController.cs
using App.Business.DTOs.CategoryDTOs;
using App.Business.Services.Abstract;
using App.Persistence.Data.Entity;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        ICategoryService _categoryService;
        IMapper _mapper;

        public CategoryController(ICategoryService categoryService, IMapper mapper)
        {
            _categoryService = categoryService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var categories = _categoryService.GetAll();
            return View(categories);
        }

        //CREATE
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateOrEditCategoryDto categoryDto)
        {
            if (categoryDto == null) { return RedirectToAction("Index"); }
            var category = _mapper.Map<Category>(categoryDto);

            if (ModelState.IsValid)
            {
                _categoryService.Insert(category);
                _categoryService.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }
        //EDIT
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == 0) { return RedirectToAction("Index"); }

            var category = _categoryService.GetById(id);

            if (category == null)
            { return RedirectToAction("Index"); }

            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (category == null) { return RedirectToAction("Index"); }

            if (ModelState.IsValid)
            {
                _categoryService.Update(category);
                _categoryService.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }
        //DELETE
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == 0) { return RedirectToAction("Index"); }

            var category = _categoryService.GetById(id);

            if (category == null)
            { return RedirectToAction("Index"); }

            return View(category);
        }


        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int id)
        {
            if (id == 0) { return RedirectToAction("Index"); }

            _categoryService.DeleteById(id);
            _categoryService.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Search(string query, int page)
        {
            return View();
        }

        public IActionResult Detail(int id)
        {
            return View();
        }

    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace App.Web.Mvc.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Travel(int id, int page)
        {
            return View();
        }
        public IActionResult Weekends(int id, int page)
        {
            return View();
        }
        public IActionResult Lifestyle(int id, int page)
        {
            return View();
        }
        public IActionResult Explore(int id, int page)
        {
            return View();
        }
        public IActionResult Health(int id, int page)
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/ViewComponents/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.ViewComponents
{
    public class NavbarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Views/Category/Explore.cshtml
@await Component.InvokeAsync("Navbar")

<div class="breadcrumb-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center">
                    <h2 class="lg-title">Explore</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f1.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-extra text-sm text-uppercase letter-spacing-1">Explore</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">The best soft chocolate chip cookies</a></h3>

                            <span class=" text-muted  text-capitalize">September 15, 2019</span>
                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f2.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">How to Make the Best Baked Oatmeal</a></h3>

                            <span class=" text-muted  text-capitalize">August 05, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f8.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">5 ingredient cilantro vinaigrette</a></h3>

                            <span class=" text-muted  text-capitalize">April 22, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f3.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">The best soft chocolate chip cookies</a></h3>

                            <span class=" text-muted  text-capitalize">September 10, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f4.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">How to Make the Best Baked Oatmeal</a></h3>
                            <span class=" text-muted  text-capitalize">January 04, 2019</span>
                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f5.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">5 ingredient cilantro vinaigrette</a></h3>
                            <span class=" text-muted  text-capitalize">March 17, 2019</span>
                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f6.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">5 ingredient cilantro vinaigrette</a></h3>

                            <span class=" text-muted  text-capitalize">July 28, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f7.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">The best soft chocolate chip cookies</a></h3>

                            <span class=" text-muted  text-capitalize">October 02, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f8.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">How to Make the Best Baked Oatmeal</a></h3>

                            <span class=" text-muted  text-capitalize">September 15, 2019</span>

                        </article>
                    </div>
                </div>

                <div class="pagination mt-5 pt-4">
                    <ul class="list-inline">
                        <li class="list-inline-item"><a href="#" class="active">1</a></li>
                        <li class="list-inline-item"><a href="#">2</a></li>
                        <li class="list-inline-item"><a href="#">3</a></li>
                        <li class="list-inline-item"><a href="#" class="prev-posts"><i class="ti-arrow-right"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div class="sidebar sidebar-right">
                    <div class="sidebar-wrap mt-5 mt-lg-0">
                        <div class="sidebar-widget about mb-5 text-center p-3">
                            <div class="about-author">
                                <img src="~/dist/images/author.jpg" alt="" class="img-fluid">
                            </div>
                            <h4 class="mb-0 mt-4">Liam Mason</h4>
                            <p>Explore Blogger</p>
                            <p>I'm Liam, last year I decided to quit my job and travel the world. You can follow my journey on this blog!</p>
                            <img src="Img/liammason.png" alt="" class="img-fluid">
                        </div>

                        <div class="sidebar-widget follow mb-5 text-center">
                            <h4 class="text-center widget-title">Follow Me</h4>
                            <div class="follow-socials">
                                <a href="https://www.facebook.com/" target="_blank"><i class="ti-facebook"></i></a>
                                <a href="https://twitter.com/" target="_blank"><i class="ti-twitter"></i></a>
                                <a href="https://www.instagram.com/" target="_blank"><i class="ti-instagram"></i></a>
                                <a href="https://www.youtube.com/" target="_blank"><i class="ti-youtube"></i></a>
                                <a href="https://tr.pinterest.com/" target="_blank"><i class="ti-pinterest"></i></a>
                            </div>
                        </div>

                        <div class="sidebar-widget mb-5 ">
                            <h4 class="text-center widget-title">Trending Posts</h4>

                            <div class="sidebar-post-item-big">
                                <a asp-controller="Blog" asp-action="Detail"><img src="~/dist/images/news/img-1.jpg" alt="" class="img-fluid"></a>
                                <div class="mt-3 media-body">
                                    <span class="text-muted letter-spacing text-uppercase font-sm">September 10, 2019</span>
                                    <h4><a asp-controller="Blog" asp-action="Detail">Meeting With Clarissa, Founder Of Purple Conversation App</a></h4>
                                </div>
                            </div>

                            <div class="media border-bottom py-3 sidebar-post-item">
                                <a href="#"><img class="mr-4" src="Img/news/thumb-1.jpg" alt=""></a>
                                <div class="media-body">
                                    <span class="text-muted letter-spacing text-uppercase font-sm">September 10, 2019</span>
                                    <h4><a asp-controller="Blog" asp-action="Detail">Thoughtful living in los Angeles</a></h4>
                                </div>
                            </div>

                            <div class="media py-3 sidebar-post-item">
                                <a href="#"><img class="mr-4" src="Img/news/thumb-2.jpg" alt=""></a>
                                <div class="media-body">
                                    <span class="text-muted letter-spacing text-uppercase font-sm">September 10, 2019</span>
                                    <h4><a asp-controller="Blog" asp-action="Detail">Vivamus molestie gravida turpis.</a></h4>
                                </div>
                            </div>
                        </div>


                        <div class="sidebar-widget category mb-5">
                            <h4 class="text-center widget-title">Catgeories</h4>
                            <ul class="list-unstyled">
                                <li class="align-items-center d-flex justify-content-between">
                                    <a href="#">Innovation</a>
                                    <span>14</span>
                                </li>
                                <li class="align-items-center d-flex justify-content-between">
                                    <a href="#">Software</a>
                                    <span>2</span>
                                </li>
                                <li class="align-items-center d-flex justify-content-between">
                                    <a href="#">Social</a>
                                    <span>10</span>
                                </li>
                                <li class="align-items-center d-flex justify-content-between">
                                    <a href="#">Trends</a>
                                    <span>5</span>
                                </li>
                            </ul>
                        </div>

                        <div class="sidebar-widget subscribe mb-5">
                            <h4 class="text-center widget-title">Newsletter</h4>
                            <input type="text" class="form-control" placeholder="Email Address">
                            <a href="#" class="btn btn-primary d-block mt-3">Sign Up</a>
                        </div>

                        <div class="sidebar-widget sidebar-adv mb-5">
                            <a href="#"><img src="~/dist/images/sidebar-banner3.png" alt="" class="img-fluid w-100"></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@await Component.InvokeAsync("Footer")

AspNetMvcBlog/App.Web.Mvc/Views/Category/Health.cshtml
@await Component.InvokeAsync("Navbar")

<div class="breadcrumb-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center">
                    <h2 class="lg-title">Health</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f1.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-extra text-sm text-uppercase letter-spacing-1">Health</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">The best soft chocolate chip cookies</a></h3>

                            <span class=" text-muted  text-capitalize">September 15, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f2.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Health</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">How to Make the Best Baked Oatmeal</a></h3>

                            <span class=" text-muted  text-capitalize">August 05, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f8.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">Health</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">5 ingredient cilantro vinaigrette</a></h3>

                            <span class=" text-muted  text-capitalize">April 22, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f3.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Health</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">The best soft chocolate chip cookies</a></h3>

                            <span class=" text-muted  text-capitalize">September 10, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f4.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Health</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">How to Make the Best Baked Oatmeal</a></h3>
                            <span class=" text-muted  text-capitalize">January 04, 2019</span>
                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f5.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Health</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">5 ingredient cilantro vinaigrette</a></h3>
                            <span class=" text-muted  text-capitalize">March 17, 2019</span>
                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f6.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">Health</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">5 ingredient cilantro vinaigrette</a></h3>

                            <span class=" text-muted  text-capitalize">July 28, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f7.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Health</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">The best soft chocolate chip cookies</a></h3>

                            <span class=" text-muted  text-capitalize">October 02, 2019</span>

                        </article>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <article class="post-grid mb-5">
                            <div class="post-thumb mb-4">
                                <img src="~/dist/images/news/f8.jpg" alt="" class="img-fluid w-100">
                            </div>
                            <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Health</span>
                            <h3 class="post-title mt-1"><a asp-controller="Blog" asp-action="Detail">How to Make the Best Baked Oatmeal</a></h3>

                            <span class=" text-muted  text-capitalize">September 15, 2019</span>

                        </article>
                    </div>
                </div>

                <div class="pagination mt-5 pt-4">
                    <ul class="list-inline">
                        <li class="list-inline-item"><a href="#" class="active">1</a></li>
                        <li class="list-inline-item"><a href="#">2</a></li>
                        <li class="list-inline-item"><a href="#">3</a></li>
                        <li class="list-inline-item"><a href="#" class="prev-posts"><i class="ti-arrow-right"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div class="sidebar sidebar-right">
                    <div class="sidebar-wrap mt-5 mt-lg-0">
                        <div class="sidebar-widget about mb-5 text-center p-3">
                            <div class="about-author">
                                <img src="~/dist/images/author.jpg" alt="" class="img-fluid">
                            </div>
                            <h4 class="mb-0 mt-4">Liam Mason</h4>
                            <p>Health Blogger</p>
                            <p>I'm Liam, last year I decided to quit my job and travel the world. You can follow my journey on this blog!</p>
                            <img src="Img/liammason.png" alt="" class="img-fluid">
                        </div>

                        <div class="sidebar-widget follow mb-5 text-center">
                            <h4 class="text-center widget-title">Follow Me</h4>
                            <div class="follow-socials">
                                <a href="https://www.facebook.com/" target="_blank"><i class="ti-facebook"></i></a>
                                <a href="https://twitter.com/" target="_blank"><i class="ti-twitter"></i></a>
                                <a href="https://www.instagram.com/" target="_blank"><i class="ti-instagram"></i></a>
                                <a href="https://www.youtube.com/" target="_blank"><i class="ti-youtube"></i></a>
                                <a href="https://tr.pinterest.com/" target="_blank"><i class="ti-pinterest"></i></a>
                            </div>
                        </div>

                        <div class="sidebar-widget mb-5 ">
                            <h4 class="text-center widget-title">Trending Posts</h4>

                            <div class="sidebar-post-item-big">
                                <a asp-controller="Blog" asp-action="Detail"><img src="~/dist/images/news/img-1.jpg" alt="" class="img-fluid"></a>
                                <div class="mt-3 media-body">
                                    <span class="text-muted letter-spacing text-uppercase font-sm">September 10, 2019</span>
                                    <h4><a asp-controller="Blog" asp-action="Detail">Meeting With Clarissa, Founder Of Purple Conversation App</a></h4>
                                </div>
                            </div>

                            <div class="media border-bottom py-3 sidebar-post-item">
                                <a href="#"><img class="mr-4" src="Img/news/thumb-1.jpg" alt=""></a>
                                <div class="media-body">
                                    <span class="text-muted letter-spacing text-uppercase font-sm">September 10, 2019</span>
                                    <h4><a asp-controller="Blog" asp-action="Detail">Thoughtful living in los Angeles</a></h4>
                                </div>
                            </div>

                            <div class="media py-3 sidebar-post-item">
                                <a href="#"><img class="mr-4" src="Img/news/thumb-2.jpg" alt=""></a>
                                <div class="media-body">
                                    <span class="text-muted letter-spacing text-uppercase font-sm">September 10, 2019</span>
                                    <h4><a asp-controller="Blog" asp-action="Detail">Vivamus molestie gravida turpis.</a></h4>
                                </div>
                            </div>
                        </div>


                        <div class="sidebar-widget category mb-5">
                            <h4 class="text-center widget-title">Catgeories</h4>
                            <ul class="list-unstyled">
                                <li class="align-items-center d-flex justify-content-between">
                                    <a href="#">Innovation</a>
                                    <span>14</span>
                                </li>
                                <li class="align-items-center d-flex justify-content-between">
                                    <a href="#">Software</a>
                                    <span>2</span>
                                </li>
                                <li class="align-items-center d-flex justify-content-between">
                                    <a href="#">Social</a>
                                    <span>10</span>
                                </li>
                                <li class="align-items-center d-flex justify-content-between">
                                    <a href="#">Trends</a>
                                    <span>5</span>
                                </li>
                            </ul>
                        </div>

                        <div class="sidebar-widget subscribe mb-5">
                            <h4 class="text-center widget-title">Newsletter</h4>
                            <input type="text" class="form-control" placeholder="Email Address">
                            <a href="#" class="btn btn-primary d-block mt-3">Sign Up</a>
                        </div>

                        <div class="sidebar-widget sidebar-adv mb-5">
                            <a href="#"><img src="~/dist/images/sidebar-banner3.png" alt="" class="img-fluid w-100"></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@await Component.InvokeAsync("Footer")